name: Build Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-check:
    name: Build Check
    uses: ./.github/workflows/deploy.yml
    with:
      caller_workflow: ci
    secrets: inherit 